#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
完整版施工方案生成器
生成详细、专业的施工方案文档（非大纲）
"""

import sys
import argparse
from pathlib import Path
from datetime import datetime

class CompletePlanGenerator:
    """生成完整版施工方案"""
    
    def __init__(self, output_dir=None):
        if output_dir is None:
            output_dir = Path.home() / "Documents" / "施工方案"
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_deep_excavation_plan(self, project_info):
        """生成完整深基坑施工方案"""
        project_name = project_info.get('name', '新建工程')
        depth = project_info.get('depth', 10)
        area = project_info.get('area', '50000')
        structure = project_info.get('structure', '框架结构')
        
        content = []
        
        # 封面
        content.append("=" * 80)
        content.append(" ".center(80))
        content.append(f"{project_name}".center(80))
        content.append(" ".center(80))
        content.append("深基坑工程施工方案".center(80))
        content.append(" ".center(80))
        content.append("=" * 80)
        content.append("")
        content.append(f"编制单位：{project_name}项目部".center(80))
        content.append(f"编制日期：{datetime.now().strftime('%Y年%m月%d日')}".center(80))
        content.append("")
        content.append("=" * 80)
        content.append("")
        
        # 目录
        content.append("目  录".center(80))
        content.append("")
        content.append("一、编制依据.................................................................................... 1")
        content.append("二、工程概况.................................................................................... 2")
        content.append("三、施工部署.................................................................................... 4")
        content.append("四、基坑支护设计................................................................................ 6")
        content.append("五、基坑降水、排水方案.......................................................................... 8")
        content.append("六、土方开挖方案................................................................................ 10")
        content.append("七、基坑监测方案................................................................................ 12")
        content.append("八、安全保证措施................................................................................ 14")
        content.append("九、文明施工及环境保护措施...................................................................... 16")
        content.append("十、应急预案.................................................................................... 17")
        content.append("")
        content.append("=" * 80)
        content.append("")
        
        # 一、编制依据
        content.append("一、编制依据")
        content.append("=" * 80)
        content.append("")
        content.append("1.1 相关法律法规")
        content.append("    (1) 《中华人民共和国建筑法》")
        content.append("    (2) 《中华人民共和国安全生产法》")
        content.append("    (3) 《建设工程安全生产管理条例》（国务院令第393号）")
        content.append("    (4) 《危险性较大的分部分项工程安全管理规定》（住建部令第37号）")
        content.append("")
        content.append("1.2 主要规范标准")
        content.append("    (1) 《建筑地基基础设计规范》GB 50007-2011")
        content.append("    (2) 《建筑基坑支护技术规程》JGJ 120-2012")
        content.append("    (3) 《建筑深基坑工程施工安全技术规范》JGJ 311-2013")
        content.append("    (4) 《建筑基坑工程监测技术标准》GB 50497-2019")
        content.append("    (5) 《建筑地基基础工程施工质量验收标准》GB 50202-2018")
        content.append("    (6) 《建筑施工安全检查标准》JGJ 59-2011")
        content.append("    (7) 《建筑机械使用安全技术规程》JGJ 33-2012")
        content.append("")
        content.append("1.3 其他依据")
        content.append("    (1) 本项目岩土工程勘察报告")
        content.append("    (2) 本项目设计图纸及设计交底文件")
        content.append("    (3) 本项目施工合同及招标文件")
        content.append("    (4) 本单位质量管理体系文件")
        content.append("")
        
        # 二、工程概况
        content.append("二、工程概况")
        content.append("=" * 80)
        content.append("")
        content.append("2.1 工程基本信息")
        content.append(f"    工程名称：{project_name}")
        content.append(f"    建筑面积：{area}平方米")
        content.append(f"    结构形式：{structure}")
        content.append(f"    基坑深度：{depth}米")
        content.append("    基础形式：筏板基础")
        content.append("")
        content.append("2.2 场地工程地质条件")
        content.append("    根据岩土工程勘察报告，场地地层自上而下依次为：")
        content.append("    ① 杂填土：层厚0.5～2.5m，杂色，松散，含建筑垃圾")
        content.append("    ② 粉质粘土：层厚2.0～5.0m，黄褐色，可塑，中等压缩性")
        content.append("    ③ 砂质粘性土：层厚3.0～8.0m，灰白色，硬塑，低压缩性")
        content.append("    ④ 强风化花岗岩：层厚5.0～15.0m，褐黄色，节理发育")
        content.append("")
        content.append("2.3 场地水文地质条件")
        content.append("    场地地下水类型主要为孔隙潜水，赋存于填土及砂质粘性土中。")
        content.append("    地下水位埋深：1.5～3.0m，水位年变化幅度约1.0m。")
        content.append("    地下水对混凝土结构具微腐蚀性，对钢筋混凝土结构中钢筋具微腐蚀性。")
        content.append("")
        content.append("2.4 周边环境条件")
        content.append("    (1) 东侧：距红线约15m为市政道路，有地下管线")
        content.append("    (2) 南侧：距红线约10m为既有建筑物，6层框架结构")
        content.append("    (3) 西侧：距红线约20m为待建空地")
        content.append("    (4) 北侧：距红线约12m为市政绿化带")
        content.append("")
        content.append("2.5 基坑特点及施工难点")
        content.append(f"    (1) 基坑开挖深度{depth}m，属于深基坑工程，施工风险较大")
        content.append("    (2) 场地周边环境复杂，需加强监测和保护")
        content.append("    (3) 地下水丰富，需采取有效的降水措施")
        content.append("    (4) 土方开挖量大，需合理组织土方外运")
        content.append("")
        
        # 三、施工部署
        content.append("三、施工部署")
        content.append("=" * 80)
        content.append("")
        content.append("3.1 施工目标")
        content.append("    质量目标：确保工程质量达到合格标准")
        content.append("    安全目标：杜绝重大安全事故，轻伤率控制在1‰以下")
        content.append("    工期目标：按计划完成基坑工程施工")
        content.append("    文明施工目标：创建文明工地")
        content.append("")
        content.append("3.2 施工组织机构")
        content.append("    项目经理：全面负责项目施工管理")
        content.append("    技术负责人：负责施工技术管理和质量控制")
        content.append("    安全员：负责施工现场安全管理")
        content.append("    施工员：负责现场施工组织和协调")
        content.append("    质检员：负责施工质量检查验收")
        content.append("    测量员：负责施工测量和监测")
        content.append("")
        content.append("3.3 施工进度计划")
        content.append("    第一阶段：施工准备（5天）")
        content.append("    第二阶段：降水井施工（10天）")
        content.append("    第三阶段：基坑支护施工（20天）")
        content.append("    第四阶段：土方开挖（30天）")
        content.append("    第五阶段：基础施工（40天）")
        content.append("    总工期：约105天")
        content.append("")
        content.append("3.4 劳动力计划")
        content.append("    土方工：30人")
        content.append("    支护工：20人")
        content.append("    降水工：10人")
        content.append("    钢筋工：15人")
        content.append("    混凝土工：15人")
        content.append("    机操工：8人")
        content.append("    杂工：10人")
        content.append("")
        content.append("3.5 机械设备计划")
        content.append("    反铲挖掘机（1.0m³）：4台")
        content.append("    自卸汽车（20t）：15辆")
        content.append("    塔式起重机：2台")
        content.append("    混凝土输送泵：2台")
        content.append("    钢筋加工设备：1套")
        content.append("    电焊机：6台")
        content.append("")
        
        # 四、基坑支护设计
        content.append("四、基坑支护设计")
        content.append("=" * 80)
        content.append("")
        content.append("4.1 支护方案选择")
        content.append(f"    根据本工程基坑深度{depth}m及场地条件，采用以下支护方案：")
        content.append("    东侧、南侧（临近道路和建筑物）：采用排桩+内支撑支护")
        content.append("    西侧、北侧：采用土钉墙支护")
        content.append("    基坑角部：采用加强型支护")
        content.append("")
        content.append("4.2 排桩支护设计参数")
        content.append("    支护桩：钻孔灌注桩，桩径800mm，桩间距1.2m")
        content.append("    桩长：根据计算确定，一般18～22m")
        content.append("    混凝土强度：C30")
        content.append("    主筋：16根HRB400Φ25")
        content.append("    箍筋：HPB300Φ10@200")
        content.append("    冠梁：C30混凝土，断面800×600mm")
        content.append("")
        content.append("4.3 内支撑设计")
        content.append("    支撑形式：钢筋混凝土内支撑")
        content.append("    支撑断面：主支撑800×800mm，次支撑600×600mm")
        content.append("    支撑间距：竖向2道，水平间距6m")
        content.append("    混凝土强度：C30")
        content.append("")
        content.append("4.4 土钉墙设计参数")
        content.append("    坡面：按1:0.3放坡")
        content.append("    土钉：HRB400Φ25钢筋，长度12m，间距1.5m×1.5m")
        content.append("    注浆：M20水泥砂浆，注浆压力0.4～0.6MPa")
        content.append("    面层：C20喷射混凝土，厚度80mm")
        content.append("    钢筋网：HPB300Φ6.5@200×200")
        content.append("")
        
        # 五、基坑降水、排水方案
        content.append("五、基坑降水、排水方案")
        content.append("=" * 80)
        content.append("")
        content.append("5.1 降水方案")
        content.append("    采用管井降水方案，沿基坑周边布置降水井。")
        content.append("    降水井间距：15～20m")
        content.append("    井深：低于基坑底面5～8m")
        content.append("    井径：Φ600mm，井管Φ300mm")
        content.append("    滤料：中粗砂")
        content.append("")
        content.append("5.2 降水井施工")
        content.append("    (1) 定位放线：按设计位置测放降水井点位")
        content.append("    (2) 钻孔：采用回旋钻机成孔，孔径Φ600mm")
        content.append("    (3) 下管：安装Φ300mm井管，包缠滤网")
        content.append("    (4) 填砾：井管与孔壁间填中粗砂滤料")
        content.append("    (5) 洗井：用清水冲洗，至水清砂净")
        content.append("    (6) 安装水泵：放置潜水泵，连接排水管")
        content.append("")
        content.append("5.3 基坑排水")
        content.append("    坑内排水：沿基坑底四周设排水沟，每30m设集水井")
        content.append("    排水沟断面：300×300mm，砖砌抹面")
        content.append("    集水井：800×800×1000mm，安装潜水泵抽排")
        content.append("    坑外排水：地面设截水沟，防止地表水流入基坑")
        content.append("")
        content.append("5.4 降水运行管理")
        content.append("    (1) 开挖前15天开始降水，将地下水位降至基底以下0.5m")
        content.append("    (2) 降水期间每天观测水位，记录抽水量")
        content.append("    (3) 保持连续降水，不得随意停抽")
        content.append("    (4) 基础施工完毕且回填后，方可停止降水")
        content.append("")
        
        # 六、土方开挖方案
        content.append("六、土方开挖方案")
        content.append("=" * 80)
        content.append("")
        content.append("6.1 开挖原则")
        content.append("    分层开挖，先撑后挖，严禁超挖")
        content.append("    每层开挖深度不超过2.0m")
        content.append("    开挖与支护施工密切配合")
        content.append("")
        content.append("6.2 开挖顺序")
        content.append("    总体顺序：由北向南，由东向西，分层分段开挖")
        content.append("    第一层：开挖至-2.0m，施工第一道支撑")
        content.append("    第二层：开挖至-6.0m，施工第二道支撑")
        content.append("    第三层：开挖至基底，施工垫层")
        content.append("")
        content.append("6.3 开挖方法")
        content.append("    (1) 采用反铲挖掘机开挖，人工配合修坡清底")
        content.append("    (2) 开挖坡度按设计要求，坡面及时支护")
        content.append("    (3) 机械开挖至基底以上200mm，余土人工清除")
        content.append("    (4) 开挖过程中及时排除积水")
        content.append("")
        content.append("6.4 土方运输")
        content.append("    (1) 土方及时外运，不得在坑边堆载")
        content.append("    (2) 运输道路硬化处理，设置车辆冲洗设施")
        content.append("    (3) 运输时间避开交通高峰，办理相关许可")
        content.append("    (4) 车辆密闭运输，防止遗撒污染道路")
        content.append("")
        content.append("6.5 开挖注意事项")
        content.append("    (1) 严格控制每层开挖深度，不得超挖")
        content.append("    (2) 开挖过程中加强监测，发现异常立即停止")
        content.append("    (3) 保护支护结构，机械不得碰撞")
        content.append("    (4) 基底暴露时间不宜过长，及时施工垫层")
        content.append("")
        
        # 七、基坑监测方案
        content.append("七、基坑监测方案")
        content.append("=" * 80)
        content.append("")
        content.append("7.1 监测内容")
        content.append("    (1) 基坑周边地表沉降监测")
        content.append("    (2) 支护桩（墙）顶水平位移监测")
        content.append("    (3) 支护桩（墙）深层水平位移监测")
        content.append("    (4) 支撑轴力监测")
        content.append("    (5) 地下水位监测")
        content.append("    (6) 周边建筑物沉降监测")
        content.append("    (7) 周边管线变形监测")
        content.append("")
        content.append("7.2 监测点布置")
        content.append("    地表沉降点：沿基坑周边每20m布置1个")
        content.append("    桩顶位移点：每边至少3个，间距不大于20m")
        content.append("    深层位移点：每边1～2个，测斜孔深应超过支护桩底")
        content.append("    支撑轴力点：每层支撑每边不少于2个")
        content.append("    水位观测井：每边1个，共4个")
        content.append("")
        content.append("7.3 监测频率")
        content.append("    开挖期间：每天1次")
        content.append("    底板浇筑后：每2天1次")
        content.append("    基础施工期间：每周2次")
        content.append("    出现异常情况时：加密监测，必要时连续监测")
        content.append("")
        content.append("7.4 预警值及控制值")
        content.append("    桩顶水平位移：预警值25mm，控制值35mm")
        content.append("    深层水平位移：预警值40mm，控制值50mm")
        content.append("    地表沉降：预警值25mm，控制值35mm")
        content.append("    支撑轴力：预警值设计值的80%，控制值设计值的100%")
        content.append("    周边建筑物沉降：预警值20mm，控制值30mm")
        content.append("")
        content.append("7.5 监测成果及信息反馈")
        content.append("    (1) 每次监测后及时整理数据，绘制时程曲线")
        content.append("    (2) 监测成果当天报告项目部")
        content.append("    (3) 达到预警值时立即报告，分析原因，采取措施")
        content.append("    (4) 达到控制值时启动应急预案")
        content.append("")
        
        # 八、安全保证措施
        content.append("八、安全保证措施")
        content.append("=" * 80)
        content.append("")
        content.append("8.1 组织措施")
        content.append("    (1) 建立以项目经理为首的安全生产领导小组")
        content.append("    (2) 配备专职安全员，持证上岗")
        content.append("    (3) 建立安全生产责任制，层层签订责任书")
        content.append("    (4) 定期开展安全教育培训")
        content.append("")
        content.append("8.2 技术措施")
        content.append("    (1) 严格执行先撑后挖，严禁超挖")
        content.append("    (2) 基坑周边设置1.2m高防护栏杆，张挂安全网")
        content.append("    (3) 设置专用通道，严禁攀爬支护结构")
        content.append("    (4) 临边洞口设置盖板或防护栏杆")
        content.append("    (5) 夜间施工设置充足照明和警示灯")
        content.append("")
        content.append("8.3 施工机械安全措施")
        content.append("    (1) 挖掘机作业半径内不得站人")
        content.append("    (2) 起重机作业时设置警戒区域")
        content.append("    (3) 运输车辆限速行驶，服从指挥")
        content.append("    (4) 机械定期保养，严禁带病作业")
        content.append("")
        content.append("8.4 临电安全措施")
        content.append("    (1) 采用TN-S接零保护系统，三级配电两级漏电保护")
        content.append("    (2) 配电箱统一编号，张贴接线图")
        content.append("    (3) 电工持证上岗，每日巡查记录")
        content.append("    (4) 潮湿场所使用安全电压")
        content.append("    (5) 电缆架空敷设，严禁拖地泡水")
        content.append("")
        content.append("8.5 消防安全措施")
        content.append("    (1) 配备足够灭火器，定期检查更换")
        content.append("    (2) 动火作业办理动火证，配备看火人")
        content.append("    (3) 氧气乙炔瓶间距不小于5m，距明火不小于10m")
        content.append("    (4) 严禁在工地吸烟")
        content.append("    (5) 定期开展消防演练")
        content.append("")
        
        # 九、文明施工及环保措施
        content.append("九、文明施工及环境保护措施")
        content.append("=" * 80)
        content.append("")
        content.append("9.1 文明施工措施")
        content.append("    (1) 施工现场设置围挡，实行封闭管理")
        content.append("    (2) 出入口设置洗车槽，车辆冲洗干净出场")
        content.append("    (3) 主要道路硬化，定时洒水降尘")
        content.append("    (4) 材料分类堆放整齐，标识清楚")
        content.append("    (5) 建筑垃圾及时清运，日产日清")
        content.append("")
        content.append("9.2 环境保护措施")
        content.append("    (1) 扬尘控制：裸土覆盖，洒水降尘，土方密闭运输")
        content.append("    (2) 噪声控制：选用低噪设备，合理安排作业时间")
        content.append("    (3) 污水控制：施工废水经沉淀后排放")
        content.append("    (4) 光污染控制：夜间照明定向，避免直射居民区")
        content.append("    (5) 周边保护：加强监测，发现沉降及时采取措施")
        content.append("")
        
        # 十、应急预案
        content.append("十、应急预案")
        content.append("=" * 80)
        content.append("")
        content.append("10.1 应急组织机构")
        content.append("    组长：项目经理")
        content.append("    副组长：技术负责人、安全员")
        content.append("    成员：施工员、质检员、各班组长")
        content.append("")
        content.append("10.2 应急准备")
        content.append("    (1) 建立应急抢险队伍，定期演练")
        content.append("    (2) 配备应急物资：砂袋、水泥、注浆设备、水泵等")
        content.append("    (3) 与附近医院建立绿色通道")
        content.append("    (4) 公布应急联系电话")
        content.append("")
        content.append("10.3 基坑坍塌应急处置")
        content.append("    征兆：支护结构变形加剧、地面开裂、支撑轴力异常增大")
        content.append("    措施：")
        content.append("    (1) 立即停止开挖，组织人员撤离")
        content.append("    (2) 回填反压，稳定边坡")
        content.append("    (3) 加强监测，分析原因")
        content.append("    (4) 联系设计单位，制定加固方案")
        content.append("    (5) 必要时疏散周边人员")
        content.append("")
        content.append("10.4 涌水涌砂应急处置")
        content.append("    征兆：基坑底冒水、夹砂，水位急剧下降")
        content.append("    措施：")
        content.append("    (1) 立即封堵涌水点")
        content.append("    (2) 加大降水力度，降低水头")
        content.append("    (3) 采用双液注浆止水")
        content.append("    (4) 必要时回填，待处理后再开挖")
        content.append("")
        content.append("10.5 周边建筑物沉降过大应急处置")
        content.append("    措施：")
        content.append("    (1) 加密监测，查明原因")
        content.append("    (2) 调整开挖顺序，减缓施工速度")
        content.append("    (3) 必要时进行地基加固")
        content.append("    (4) 与业主、设计、监理协商处理方案")
        content.append("")
        content.append("10.6 应急联系方式")
        content.append("    项目经理：XXX（电话：138XXXXXXXX）")
        content.append("    技术负责人：XXX（电话：139XXXXXXXX）")
        content.append("    安全员：XXX（电话：137XXXXXXXX）")
        content.append("    急救电话：120")
        content.append("    火警电话：119")
        content.append("    报警电话：110")
        content.append("")
        content.append("=" * 80)
        content.append("")
        content.append("                                    编制人：__________")
        content.append("                                    审核人：__________")
        content.append("                                    审批人：__________")
        content.append("                                    日  期：__________")
        content.append("")
        
        return "\n".join(content)
    
    def save_to_desktop(self, project_name, content):
        """保存到桌面"""
        desktop = Path.home() / "Desktop"
        filepath = desktop / f"{project_name}_深基坑施工方案_完整版.txt"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return filepath

def main():
    generator = CompletePlanGenerator()
    
    project_info = {
        'name': '深基坑示范工程',
        'depth': 12,
        'area': '80000',
        'structure': '框架剪力墙'
    }
    
    print("[开始] 正在生成完整版深基坑施工方案...")
    content = generator.generate_deep_excavation_plan(project_info)
    
    filepath = generator.save_to_desktop(project_info['name'], content)
    print(f"[完成] 方案已保存到: {filepath}")
    
    # 统计信息
    line_count = len(content.split('\n'))
    char_count = len(content)
    print(f"[信息] 方案总字数: {char_count} 字符，总行数: {line_count} 行")

if __name__ == "__main__":
    main()
